[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
blog_dapp = "DhHUJjVQUkgFFF1PANUZvmwx2CR2iVjNnXeEcWfeJFJ4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/hema/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
